apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: echo-api-key
spec:
  vaultAuthRef: openbao-auth
  type: kv-v2
  mount: secret
  path: platform-lab/echo/config
  destination:
    name: echo-api-key
    create: true
  refreshAfter: 60s
