apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-processor
  template:
    metadata:
      labels:
        app: event-processor
    spec:
      containers:
        - name: event-processor
          image: ghcr.io/vichingo/platform-lab/event-processor:latest
          env:
            - name: NATS_URL
              value: nats://nats.dev.svc.cluster.local:4222
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi
