apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: event-processor
spec:
  scaleTargetRef:
    name: event-processor
  minReplicaCount: 0
  maxReplicaCount: 5
  triggers:
    - type: nats-jetstream
      metadata:
        natsServerMonitoringEndpoint: nats-headless.dev.svc.cluster.local:8222
        account: "$G"
        stream: WEBHOOKS
        consumer: webhook-processor
        lagThreshold: "10"
