apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: dev
images:
- name: ghcr.io/vichingo/platform-lab/event-processor
  newTag: 1358bf0e0390370bb0f32344da64d1b95665f4f7
- name: ghcr.io/vichingo/platform-lab/webhook-service
  newTag: d782374568b79f96efadeeb7a884572907fa5311
