apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-lab-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vichingo/platform-lab
    targetRevision: HEAD
    path: infra-k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
