apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.traefik.io/traefik
    chart: traefik
    targetRevision: "34.x.x"
    helm:
      values: |
        ports:
          web:
            port: 8000
            exposedPort: 80
          websecure:
            port: 8443
            exposedPort: 443
        ingressRoute:
          dashboard:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
