apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://helm.releases.hashicorp.com"
    chart: vault-secrets-operator
    targetRevision: "0.x.x"
    helm:
      values: |
        defaultVaultConnection:
          enabled: true
          address: "http://host.k3d.internal:8200"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
